[package]
name = "rust-opengl"
version = "0.1.0"
authors = ["artem <artem@webart-tech.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.1"